// ============================================================
//  PointFit — Base de données aliments (foods.js)
//  ~400 aliments, valeurs pour 100g (sauf mention)
//  Sources : Ciqual 2020 (ANSES), étiquetages fabricants
//  Formule points : (cal×0.0305)+(sat×0.275)+(sugar×0.12)
//                  −(prot×0.098)−(fiber×0.07)  → min 0
// ============================================================

const FOODS_DB = [

// ══════════════════════════════════════════
//  🍗 VOLAILLES
// ══════════════════════════════════════════
{ name:“Blanc de poulet (cuit, sans peau)”,   emoji:“🍗”, cat:“Volailles”,  cal:110, prot:23.0, sat:0.4, sugar:0.0, fiber:0.0, portion:150 },
{ name:“Blanc de poulet (cru)”,               emoji:“🍗”, cat:“Volailles”,  cal:105, prot:22.0, sat:0.5, sugar:0.0, fiber:0.0, portion:150 },
{ name:“Cuisse de poulet (rôtie, sans peau)”, emoji:“🍗”, cat:“Volailles”,  cal:153, prot:20.6, sat:2.0, sugar:0.0, fiber:0.0, portion:150 },
{ name:“Cuisse de poulet (rôtie, avec peau)”, emoji:“🍗”, cat:“Volailles”,  cal:218, prot:19.0, sat:4.2, sugar:0.0, fiber:0.0, portion:150 },
{ name:“Poulet rôti entier (chair moyenne)”,  emoji:“🍗”, cat:“Volailles”,  cal:189, prot:20.0, sat:3.5, sugar:0.0, fiber:0.0, portion:150 },
{ name:“Escalope de dinde (cuite)”,           emoji:“🍗”, cat:“Volailles”,  cal:104, prot:21.5, sat:0.4, sugar:0.0, fiber:0.0, portion:150 },
{ name:“Blanc de dinde (cru)”,                emoji:“🍗”, cat:“Volailles”,  cal:99,  prot:21.8, sat:0.3, sugar:0.0, fiber:0.0, portion:150 },
{ name:“Escalope de dinde panée”,             emoji:“🍗”, cat:“Volailles”,  cal:220, prot:16.0, sat:2.5, sugar:4.0, fiber:0.5, portion:120 },
{ name:“Nuggets de poulet”,                   emoji:“🍗”, cat:“Volailles”,  cal:255, prot:14.0, sat:3.2, sugar:2.5, fiber:0.5, portion:100 },
{ name:“Canard (magret, cuit)”,               emoji:“🍗”, cat:“Volailles”,  cal:190, prot:26.0, sat:3.5, sugar:0.0, fiber:0.0, portion:150 },
{ name:“Canard (magret, avec peau, cuit)”,    emoji:“🍗”, cat:“Volailles”,  cal:338, prot:21.0, sat:10.0,sugar:0.0, fiber:0.0, portion:150 },
{ name:“Foie de volaille (cuit)”,             emoji:“🍗”, cat:“Volailles”,  cal:169, prot:24.0, sat:2.4, sugar:0.8, fiber:0.0, portion:100 },
{ name:“Pintade (cuite, sans peau)”,          emoji:“🍗”, cat:“Volailles”,  cal:148, prot:24.0, sat:1.8, sugar:0.0, fiber:0.0, portion:150 },
{ name:“Caille (cuite)”,                      emoji:“🍗”, cat:“Volailles”,  cal:228, prot:25.0, sat:5.0, sugar:0.0, fiber:0.0, portion:100 },

// ══════════════════════════════════════════
//  🥩 VIANDES ROUGES & PORC
// ══════════════════════════════════════════
{ name:“Bœuf haché 5% MG (cuit)”,            emoji:“🥩”, cat:“Viandes”,    cal:121, prot:20.0, sat:1.9, sugar:0.0, fiber:0.0, portion:125 },
{ name:“Bœuf haché 10% MG (cuit)”,           emoji:“🥩”, cat:“Viandes”,    cal:155, prot:18.5, sat:3.5, sugar:0.0, fiber:0.0, portion:125 },
{ name:“Bœuf haché 15% MG (cuit)”,           emoji:“🥩”, cat:“Viandes”,    cal:197, prot:17.0, sat:5.8, sugar:0.0, fiber:0.0, portion:125 },
{ name:“Bœuf haché 20% MG (cuit)”,           emoji:“🥩”, cat:“Viandes”,    cal:243, prot:15.5, sat:8.0, sugar:0.0, fiber:0.0, portion:125 },
{ name:“Steak de bœuf (entrecôte, grillé)”,  emoji:“🥩”, cat:“Viandes”,    cal:218, prot:24.0, sat:5.5, sugar:0.0, fiber:0.0, portion:150 },
{ name:“Steak de bœuf (rumsteck, grillé)”,   emoji:“🥩”, cat:“Viandes”,    cal:174, prot:27.0, sat:2.8, sugar:0.0, fiber:0.0, portion:150 },
{ name:“Bœuf (filet, grillé)”,               emoji:“🥩”, cat:“Viandes”,    cal:161, prot:28.0, sat:2.2, sugar:0.0, fiber:0.0, portion:150 },
{ name:“Bœuf bourguignon (plat cuisiné)”,    emoji:“🥩”, cat:“Viandes”,    cal:125, prot:12.0, sat:3.0, sugar:2.5, fiber:1.0, portion:300 },
{ name:“Veau (escalope, poêlée)”,            emoji:“🥩”, cat:“Viandes”,    cal:149, prot:24.0, sat:2.0, sugar:0.0, fiber:0.0, portion:150 },
{ name:“Veau (côte, grillée)”,               emoji:“🥩”, cat:“Viandes”,    cal:178, prot:22.0, sat:3.8, sugar:0.0, fiber:0.0, portion:150 },
{ name:“Agneau (gigot, rôti)”,               emoji:“🥩”, cat:“Viandes”,    cal:191, prot:23.0, sat:5.2, sugar:0.0, fiber:0.0, portion:150 },
{ name:“Agneau (côtelette, grillée)”,        emoji:“🥩”, cat:“Viandes”,    cal:254, prot:20.0, sat:9.0, sugar:0.0, fiber:0.0, portion:130 },
{ name:“Porc (filet mignon, cuit)”,          emoji:“🥩”, cat:“Viandes”,    cal:140, prot:23.0, sat:1.8, sugar:0.0, fiber:0.0, portion:150 },
{ name:“Porc (côte, grillée)”,               emoji:“🥩”, cat:“Viandes”,    cal:234, prot:20.0, sat:7.0, sugar:0.0, fiber:0.0, portion:150 },
{ name:“Porc (rôti)”,                        emoji:“🥩”, cat:“Viandes”,    cal:185, prot:24.0, sat:4.0, sugar:0.0, fiber:0.0, portion:150 },
{ name:“Lapin (cuit)”,                       emoji:“🐰”, cat:“Viandes”,    cal:114, prot:21.0, sat:1.0, sugar:0.0, fiber:0.0, portion:150 },
{ name:“Jambon blanc (cuit, sans couenne)”,  emoji:“🥩”, cat:“Viandes”,    cal:107, prot:17.0, sat:1.2, sugar:1.0, fiber:0.0, portion:60  },
{ name:“Jambon blanc (allégé)”,              emoji:“🥩”, cat:“Viandes”,    cal:82,  prot:15.5, sat:0.8, sugar:1.5, fiber:0.0, portion:60  },
{ name:“Jambon de pays (cru, sec)”,          emoji:“🥩”, cat:“Viandes”,    cal:268, prot:27.0, sat:5.8, sugar:0.3, fiber:0.0, portion:40  },
{ name:“Jambon de Parme”,                    emoji:“🥩”, cat:“Viandes”,    cal:250, prot:25.0, sat:5.0, sugar:0.5, fiber:0.0, portion:40  },
{ name:“Chorizo (fort)”,                     emoji:“🥩”, cat:“Viandes”,    cal:455, prot:24.0, sat:16.0,sugar:1.0, fiber:0.0, portion:30  },
{ name:“Saucisson sec”,                      emoji:“🥩”, cat:“Viandes”,    cal:480, prot:26.0, sat:18.0,sugar:0.5, fiber:0.0, portion:30  },
{ name:“Merguez (grillée)”,                  emoji:“🥩”, cat:“Viandes”,    cal:290, prot:16.0, sat:9.5, sugar:1.0, fiber:0.0, portion:80  },
{ name:“Chipolata (grillée)”,                emoji:“🥩”, cat:“Viandes”,    cal:320, prot:14.0, sat:11.0,sugar:1.5, fiber:0.5, portion:80  },
{ name:“Lardons fumés (cuits)”,              emoji:“🥓”, cat:“Viandes”,    cal:344, prot:14.0, sat:12.0,sugar:0.5, fiber:0.0, portion:50  },
{ name:“Andouillette (grillée)”,             emoji:“🥩”, cat:“Viandes”,    cal:273, prot:15.0, sat:10.0,sugar:0.0, fiber:0.0, portion:100 },
{ name:“Boudin blanc (cuit)”,                emoji:“🥩”, cat:“Viandes”,    cal:254, prot:12.0, sat:9.0, sugar:5.0, fiber:0.2, portion:100 },
{ name:“Boudin noir (cuit)”,                 emoji:“🥩”, cat:“Viandes”,    cal:310, prot:13.0, sat:11.0,sugar:6.0, fiber:0.3, portion:100 },
{ name:“Foie de veau (poêlé)”,               emoji:“🥩”, cat:“Viandes”,    cal:158, prot:22.0, sat:2.3, sugar:4.5, fiber:0.0, portion:120 },
{ name:“Foie de bœuf (poêlé)”,              emoji:“🥩”, cat:“Viandes”,    cal:161, prot:23.0, sat:2.5, sugar:4.0, fiber:0.0, portion:120 },
{ name:“Rognons de veau (cuits)”,            emoji:“🥩”, cat:“Viandes”,    cal:133, prot:18.0, sat:2.5, sugar:0.8, fiber:0.0, portion:120 },

// ══════════════════════════════════════════
//  🐟 POISSONS
// ══════════════════════════════════════════
{ name:“Saumon atlantique (filet, cuit)”,    emoji:“🐟”, cat:“Poissons”,   cal:208, prot:20.0, sat:3.0, sugar:0.0, fiber:0.0, portion:150 },
{ name:“Saumon fumé”,                        emoji:“🐟”, cat:“Poissons”,   cal:185, prot:22.0, sat:2.8, sugar:0.0, fiber:0.0, portion:80  },
{ name:“Cabillaud (dos, cuit vapeur)”,       emoji:“🐟”, cat:“Poissons”,   cal:82,  prot:18.0, sat:0.1, sugar:0.0, fiber:0.0, portion:150 },
{ name:“Cabillaud (en sauce tomate)”,        emoji:“🐟”, cat:“Poissons”,   cal:78,  prot:14.0, sat:0.3, sugar:3.5, fiber:0.5, portion:200 },
{ name:“Thon (en boîte, au naturel)”,        emoji:“🐟”, cat:“Poissons”,   cal:100, prot:23.0, sat:0.4, sugar:0.0, fiber:0.0, portion:100 },
{ name:“Thon (en boîte, à l’huile, égoutté)”,emoji:“🐟”,cat:“Poissons”,   cal:200, prot:25.0, sat:1.5, sugar:0.0, fiber:0.0, portion:100 },
{ name:“Thon rouge (frais, grillé)”,         emoji:“🐟”, cat:“Poissons”,   cal:144, prot:24.0, sat:0.8, sugar:0.0, fiber:0.0, portion:150 },
{ name:“Sardines (à l’huile, égouttées)”,    emoji:“🐟”, cat:“Poissons”,   cal:185, prot:20.0, sat:2.8, sugar:0.0, fiber:0.0, portion:100 },
{ name:“Sardines (au naturel)”,              emoji:“🐟”, cat:“Poissons”,   cal:135, prot:19.0, sat:1.8, sugar:0.0, fiber:0.0, portion:100 },
{ name:“Maquereau (filet, cuit)”,            emoji:“🐟”, cat:“Poissons”,   cal:205, prot:19.0, sat:4.0, sugar:0.0, fiber:0.0, portion:130 },
{ name:“Maquereau (fumé)”,                   emoji:“🐟”, cat:“Poissons”,   cal:305, prot:18.5, sat:8.5, sugar:0.0, fiber:0.0, portion:100 },
{ name:“Lieu noir (filet, cuit)”,            emoji:“🐟”, cat:“Poissons”,   cal:79,  prot:18.0, sat:0.1, sugar:0.0, fiber:0.0, portion:150 },
{ name:“Colin (merlu, cuit)”,                emoji:“🐟”, cat:“Poissons”,   cal:85,  prot:18.5, sat:0.2, sugar:0.0, fiber:0.0, portion:150 },
{ name:“Tilapia (filet, cuit)”,              emoji:“🐟”, cat:“Poissons”,   cal:96,  prot:20.0, sat:0.5, sugar:0.0, fiber:0.0, portion:150 },
{ name:“Sole (cuite)”,                       emoji:“🐟”, cat:“Poissons”,   cal:89,  prot:18.8, sat:0.4, sugar:0.0, fiber:0.0, portion:150 },
{ name:“Daurade (cuite)”,                    emoji:“🐟”, cat:“Poissons”,   cal:114, prot:21.0, sat:1.2, sugar:0.0, fiber:0.0, portion:150 },
{ name:“Bar (loup, cuit)”,                   emoji:“🐟”, cat:“Poissons”,   cal:97,  prot:19.0, sat:0.8, sugar:0.0, fiber:0.0, portion:150 },
{ name:“Truite (filet, cuit)”,               emoji:“🐟”, cat:“Poissons”,   cal:119, prot:20.0, sat:1.2, sugar:0.0, fiber:0.0, portion:150 },
{ name:“Truite fumée”,                       emoji:“🐟”, cat:“Poissons”,   cal:170, prot:22.5, sat:2.0, sugar:0.0, fiber:0.0, portion:80  },
{ name:“Hareng (fumé)”,                      emoji:“🐟”, cat:“Poissons”,   cal:233, prot:21.0, sat:5.0, sugar:0.0, fiber:0.0, portion:100 },
{ name:“Anchois (à l’huile)”,                emoji:“🐟”, cat:“Poissons”,   cal:210, prot:23.0, sat:3.5, sugar:0.0, fiber:0.0, portion:30  },
{ name:“Flétan (cuit)”,                      emoji:“🐟”, cat:“Poissons”,   cal:140, prot:21.0, sat:1.5, sugar:0.0, fiber:0.0, portion:150 },
{ name:“Crevettes cuites (décortiquées)”,    emoji:“🦐”, cat:“Poissons”,   cal:99,  prot:21.0, sat:0.2, sugar:0.0, fiber:0.0, portion:100 },
{ name:“Crevettes roses (cuites)”,           emoji:“🦐”, cat:“Poissons”,   cal:89,  prot:19.5, sat:0.2, sugar:0.0, fiber:0.0, portion:100 },
{ name:“Moules (cuites)”,                    emoji:“🦪”, cat:“Poissons”,   cal:86,  prot:14.0, sat:0.5, sugar:1.5, fiber:0.0, portion:200 },
{ name:“Huîtres (crues)”,                    emoji:“🦪”, cat:“Poissons”,   cal:70,  prot:9.0,  sat:0.5, sugar:3.5, fiber:0.0, portion:100 },
{ name:“Saint-Jacques (noix, poêlée)”,       emoji:“🦪”, cat:“Poissons”,   cal:88,  prot:17.0, sat:0.3, sugar:0.0, fiber:0.0, portion:100 },
{ name:“Calmar (cuit)”,                      emoji:“🦑”, cat:“Poissons”,   cal:92,  prot:15.5, sat:0.4, sugar:0.8, fiber:0.0, portion:100 },
{ name:“Crabe (en conserve)”,                emoji:“🦀”, cat:“Poissons”,   cal:84,  prot:18.0, sat:0.2, sugar:0.0, fiber:0.0, portion:100 },
{ name:“Homard (cuit)”,                      emoji:“🦞”, cat:“Poissons”,   cal:90,  prot:19.0, sat:0.2, sugar:0.0, fiber:0.0, portion:150 },
{ name:“Surimi (bâtonnets)”,                 emoji:“🐟”, cat:“Poissons”,   cal:95,  prot:8.5,  sat:0.3, sugar:5.0, fiber:0.0, portion:100 },
{ name:“Poisson pané (filet, cuit)”,         emoji:“🐟”, cat:“Poissons”,   cal:195, prot:13.5, sat:2.5, sugar:8.0, fiber:0.5, portion:100 },

// ══════════════════════════════════════════
//  🥚 ŒUFS
// ══════════════════════════════════════════
{ name:“Œuf entier (cuit, dur)”,             emoji:“🥚”, cat:“Œufs”,       cal:143, prot:12.6, sat:3.1, sugar:0.4, fiber:0.0, portion:60  },
{ name:“Œuf entier (cru)”,                   emoji:“🥚”, cat:“Œufs”,       cal:147, prot:12.5, sat:3.2, sugar:0.4, fiber:0.0, portion:60  },
{ name:“Œuf entier (poché / à la coque)”,    emoji:“🥚”, cat:“Œufs”,       cal:147, prot:12.5, sat:3.2, sugar:0.4, fiber:0.0, portion:60  },
{ name:“Blanc d’œuf (cuit)”,                 emoji:“🥚”, cat:“Œufs”,       cal:52,  prot:10.9, sat:0.0, sugar:0.7, fiber:0.0, portion:40  },
{ name:“Jaune d’œuf”,                        emoji:“🥚”, cat:“Œufs”,       cal:322, prot:15.9, sat:9.6, sugar:0.3, fiber:0.0, portion:20  },
{ name:“Omelette nature (2 œufs, beurre)”,   emoji:“🍳”, cat:“Œufs”,       cal:189, prot:13.0, sat:5.5, sugar:0.5, fiber:0.0, portion:120 },
{ name:“Œufs brouillés (lait + beurre)”,     emoji:“🍳”, cat:“Œufs”,       cal:175, prot:11.0, sat:5.0, sugar:1.5, fiber:0.0, portion:120 },
{ name:“Œufs au plat (beurre)”,              emoji:“🍳”, cat:“Œufs”,       cal:196, prot:12.5, sat:6.0, sugar:0.4, fiber:0.0, portion:120 },

// ══════════════════════════════════════════
//  🧀 PRODUITS LAITIERS & FROMAGES
// ══════════════════════════════════════════
{ name:“Lait entier (3,5%)”,                 emoji:“🥛”, cat:“Laitiers”,   cal:64,  prot:3.3,  sat:2.0, sugar:4.8, fiber:0.0, portion:250 },
{ name:“Lait demi-écrémé (1,5%)”,            emoji:“🥛”, cat:“Laitiers”,   cal:46,  prot:3.2,  sat:0.9, sugar:4.7, fiber:0.0, portion:250 },
{ name:“Lait écrémé (0%)”,                   emoji:“🥛”, cat:“Laitiers”,   cal:34,  prot:3.4,  sat:0.1, sugar:4.9, fiber:0.0, portion:250 },
{ name:“Lait d’amande (nature)”,             emoji:“🥛”, cat:“Laitiers”,   cal:24,  prot:0.5,  sat:0.1, sugar:3.0, fiber:0.5, portion:250 },
{ name:“Lait d’avoine”,                      emoji:“🥛”, cat:“Laitiers”,   cal:44,  prot:1.2,  sat:0.2, sugar:4.0, fiber:0.8, portion:250 },
{ name:“Lait de soja (nature)”,              emoji:“🥛”, cat:“Laitiers”,   cal:40,  prot:3.3,  sat:0.3, sugar:2.4, fiber:0.4, portion:250 },
{ name:“Yaourt nature 0% (Danone/Activia)”,  emoji:“🥛”, cat:“Laitiers”,   cal:41,  prot:4.3,  sat:0.1, sugar:5.1, fiber:0.0, portion:125 },
{ name:“Yaourt nature entier”,               emoji:“🥛”, cat:“Laitiers”,   cal:61,  prot:3.8,  sat:1.8, sugar:4.7, fiber:0.0, portion:125 },
{ name:“Yaourt aux fruits (sucré)”,          emoji:“🥛”, cat:“Laitiers”,   cal:96,  prot:3.5,  sat:1.0, sugar:14.0,fiber:0.0, portion:125 },
{ name:“Yaourt grec nature (10%)”,           emoji:“🥛”, cat:“Laitiers”,   cal:115, prot:9.0,  sat:3.5, sugar:3.8, fiber:0.0, portion:150 },
{ name:“Yaourt grec 0%”,                     emoji:“🥛”, cat:“Laitiers”,   cal:55,  prot:9.0,  sat:0.1, sugar:3.7, fiber:0.0, portion:150 },
{ name:“Skyr nature (Arla, Siggi’s…)”,       emoji:“🥛”, cat:“Laitiers”,   cal:57,  prot:9.9,  sat:0.1, sugar:4.2, fiber:0.0, portion:150 },
{ name:“Fromage blanc nature 0%”,            emoji:“🥛”, cat:“Laitiers”,   cal:42,  prot:7.2,  sat:0.1, sugar:3.6, fiber:0.0, portion:100 },
{ name:“Fromage blanc nature 20%”,           emoji:“🥛”, cat:“Laitiers”,   cal:79,  prot:7.0,  sat:2.0, sugar:3.8, fiber:0.0, portion:100 },
{ name:“Fromage blanc nature 40%”,           emoji:“🥛”, cat:“Laitiers”,   cal:113, prot:6.4,  sat:3.8, sugar:3.5, fiber:0.0, portion:100 },
{ name:“Cottage cheese (nature)”,            emoji:“🥛”, cat:“Laitiers”,   cal:103, prot:12.5, sat:1.4, sugar:3.4, fiber:0.0, portion:100 },
{ name:“Ricotta”,                            emoji:“🧀”, cat:“Laitiers”,   cal:174, prot:11.3, sat:7.5, sugar:0.3, fiber:0.0, portion:80  },
{ name:“Crème fraîche épaisse 30%”,          emoji:“🥛”, cat:“Laitiers”,   cal:292, prot:2.5,  sat:18.0,sugar:3.0, fiber:0.0, portion:30  },
{ name:“Crème fraîche légère 15%”,           emoji:“🥛”, cat:“Laitiers”,   cal:148, prot:2.9,  sat:7.0, sugar:3.5, fiber:0.0, portion:30  },
{ name:“Crème liquide entière 30%”,          emoji:“🥛”, cat:“Laitiers”,   cal:300, prot:2.1,  sat:19.0,sugar:2.8, fiber:0.0, portion:30  },
{ name:“Emmental (râpé)”,                    emoji:“🧀”, cat:“Fromages”,   cal:382, prot:28.0, sat:15.6,sugar:0.5, fiber:0.0, portion:30  },
{ name:“Comté”,                              emoji:“🧀”, cat:“Fromages”,   cal:409, prot:27.5, sat:17.5,sugar:0.2, fiber:0.0, portion:30  },
{ name:“Gruyère”,                            emoji:“🧀”, cat:“Fromages”,   cal:393, prot:27.0, sat:17.0,sugar:0.3, fiber:0.0, portion:30  },
{ name:“Camembert (45% MG)”,                 emoji:“🧀”, cat:“Fromages”,   cal:272, prot:17.0, sat:13.5,sugar:0.5, fiber:0.0, portion:40  },
{ name:“Brie de Meaux”,                      emoji:“🧀”, cat:“Fromages”,   cal:334, prot:20.0, sat:17.0,sugar:0.5, fiber:0.0, portion:40  },
{ name:“Roquefort”,                          emoji:“🧀”, cat:“Fromages”,   cal:369, prot:21.5, sat:17.0,sugar:0.3, fiber:0.0, portion:30  },
{ name:“Feta”,                               emoji:“🧀”, cat:“Fromages”,   cal:264, prot:14.0, sat:12.0,sugar:0.5, fiber:0.0, portion:40  },
{ name:“Mozzarella (boule, lait vache)”,     emoji:“🧀”, cat:“Fromages”,   cal:254, prot:17.5, sat:10.0,sugar:1.0, fiber:0.0, portion:50  },
{ name:“Mozzarella di bufala”,               emoji:“🧀”, cat:“Fromages”,   cal:285, prot:17.0, sat:13.0,sugar:0.8, fiber:0.0, portion:50  },
{ name:“Parmesan (râpé)”,                    emoji:“🧀”, cat:“Fromages”,   cal:431, prot:38.0, sat:16.0,sugar:0.0, fiber:0.0, portion:15  },
{ name:“Cheddar”,                            emoji:“🧀”, cat:“Fromages”,   cal:403, prot:25.0, sat:20.0,sugar:0.1, fiber:0.0, portion:30  },
{ name:“Reblochon”,                          emoji:“🧀”, cat:“Fromages”,   cal:330, prot:19.0, sat:16.0,sugar:0.5, fiber:0.0, portion:40  },
{ name:“Saint-Nectaire”,                     emoji:“🧀”, cat:“Fromages”,   cal:330, prot:21.0, sat:15.0,sugar:0.5, fiber:0.0, portion:40  },
{ name:“Chèvre frais (bûche)”,               emoji:“🧀”, cat:“Fromages”,   cal:230, prot:13.5, sat:10.5,sugar:0.5, fiber:0.0, portion:40  },
{ name:“Fromage de chèvre sec”,              emoji:“🧀”, cat:“Fromages”,   cal:452, prot:29.0, sat:22.0,sugar:0.5, fiber:0.0, portion:30  },
{ name:“Boursin (ail & fines herbes)”,       emoji:“🧀”, cat:“Fromages”,   cal:383, prot:7.0,  sat:24.0,sugar:2.0, fiber:0.0, portion:30  },
{ name:“Philadelphia (nature)”,              emoji:“🧀”, cat:“Fromages”,   cal:342, prot:5.5,  sat:19.0,sugar:3.5, fiber:0.0, portion:30  },
{ name:“Fromage fondu (La Vache qui rit)”,   emoji:“🧀”, cat:“Fromages”,   cal:233, prot:9.5,  sat:12.0,sugar:4.5, fiber:0.0, portion:21  },

// ══════════════════════════════════════════
//  🍚 FÉCULENTS & CÉRÉALES
// ══════════════════════════════════════════
{ name:“Riz blanc (cuit à l’eau)”,           emoji:“🍚”, cat:“Féculents”,  cal:130, prot:2.7,  sat:0.1, sugar:0.1, fiber:0.4, portion:150 },
{ name:“Riz complet (cuit)”,                 emoji:“🍚”, cat:“Féculents”,  cal:123, prot:2.7,  sat:0.1, sugar:0.3, fiber:1.8, portion:150 },
{ name:“Riz basmati (cuit)”,                 emoji:“🍚”, cat:“Féculents”,  cal:126, prot:2.6,  sat:0.1, sugar:0.1, fiber:0.4, portion:150 },
{ name:“Riz thaï / jasmin (cuit)”,           emoji:“🍚”, cat:“Féculents”,  cal:127, prot:2.5,  sat:0.1, sugar:0.1, fiber:0.3, portion:150 },
{ name:“Riz sauvage (cuit)”,                 emoji:“🍚”, cat:“Féculents”,  cal:101, prot:4.0,  sat:0.1, sugar:0.7, fiber:1.8, portion:150 },
{ name:“Pâtes blanches (cuites)”,            emoji:“🍝”, cat:“Féculents”,  cal:131, prot:5.0,  sat:0.2, sugar:0.6, fiber:1.8, portion:200 },
{ name:“Pâtes complètes (cuites)”,           emoji:“🍝”, cat:“Féculents”,  cal:124, prot:5.4,  sat:0.2, sugar:0.5, fiber:3.5, portion:200 },
{ name:“Pâtes aux œufs (cuites)”,            emoji:“🍝”, cat:“Féculents”,  cal:138, prot:5.4,  sat:0.4, sugar:0.8, fiber:1.5, portion:200 },
{ name:“Gnocchis (nature, cuits)”,           emoji:“🍝”, cat:“Féculents”,  cal:132, prot:3.0,  sat:0.3, sugar:1.5, fiber:1.0, portion:200 },
{ name:“Quinoa (cuit)”,                      emoji:“🌾”, cat:“Féculents”,  cal:120, prot:4.4,  sat:0.2, sugar:0.9, fiber:2.8, portion:150 },
{ name:“Boulgour (cuit)”,                    emoji:“🌾”, cat:“Féculents”,  cal:83,  prot:3.1,  sat:0.1, sugar:0.1, fiber:4.5, portion:150 },
{ name:“Semoule de blé (cuite)”,             emoji:“🌾”, cat:“Féculents”,  cal:112, prot:3.8,  sat:0.1, sugar:0.4, fiber:1.3, portion:150 },
{ name:“Couscous (semoule fine, cuit)”,      emoji:“🌾”, cat:“Féculents”,  cal:112, prot:3.8,  sat:0.1, sugar:0.4, fiber:1.4, portion:200 },
{ name:“Millet (cuit)”,                      emoji:“🌾”, cat:“Féculents”,  cal:119, prot:3.5,  sat:0.2, sugar:0.0, fiber:1.3, portion:150 },
{ name:“Sarrasin / Kasha (cuit)”,            emoji:“🌾”, cat:“Féculents”,  cal:92,  prot:3.4,  sat:0.2, sugar:0.9, fiber:2.7, portion:150 },
{ name:“Polenta (cuite)”,                    emoji:“🌾”, cat:“Féculents”,  cal:70,  prot:1.7,  sat:0.1, sugar:0.4, fiber:0.8, portion:200 },
{ name:“Flocons d’avoine (secs)”,            emoji:“🌾”, cat:“Féculents”,  cal:370, prot:13.0, sat:1.4, sugar:1.0, fiber:10.0,portion:50  },
{ name:“Muesli (sans sucre ajouté)”,         emoji:“🌾”, cat:“Féculents”,  cal:350, prot:9.0,  sat:1.5, sugar:10.0,fiber:8.0, portion:50  },
{ name:“Muesli (avec fruits secs, sucré)”,   emoji:“🌾”, cat:“Féculents”,  cal:390, prot:8.0,  sat:2.0, sugar:22.0,fiber:6.0, portion:50  },
{ name:“Corn flakes (Kellogg’s)”,            emoji:“🌾”, cat:“Féculents”,  cal:377, prot:6.5,  sat:0.4, sugar:8.0, fiber:3.0, portion:40  },
{ name:“Special K (Kellogg’s)”,              emoji:“🌾”, cat:“Féculents”,  cal:373, prot:15.0, sat:0.5, sugar:17.0,fiber:3.5, portion:40  },
{ name:“Galette de riz soufflé (nature)”,    emoji:“🌾”, cat:“Féculents”,  cal:381, prot:7.0,  sat:0.5, sugar:1.2, fiber:2.3, portion:9   },
{ name:“Pain blanc (baguette tradition)”,    emoji:“🥖”, cat:“Féculents”,  cal:270, prot:8.5,  sat:0.5, sugar:2.5, fiber:2.7, portion:40  },
{ name:“Pain complet (farine T150)”,         emoji:“🍞”, cat:“Féculents”,  cal:247, prot:9.0,  sat:0.6, sugar:3.5, fiber:6.0, portion:40  },
{ name:“Pain de seigle”,                     emoji:“🍞”, cat:“Féculents”,  cal:233, prot:6.8,  sat:0.4, sugar:2.8, fiber:7.0, portion:40  },
{ name:“Pain de mie blanc (Harrys)”,         emoji:“🍞”, cat:“Féculents”,  cal:265, prot:8.0,  sat:1.2, sugar:5.5, fiber:2.5, portion:30  },
{ name:“Pain de mie complet”,               emoji:“🍞”, cat:“Féculents”,  cal:245, prot:8.5,  sat:0.9, sugar:4.5, fiber:5.5, portion:30  },
{ name:“Biscottes (Heudebert nature)”,       emoji:“🍞”, cat:“Féculents”,  cal:407, prot:12.0, sat:1.5, sugar:6.0, fiber:4.5, portion:15  },
{ name:“Pumpernickel (pain allemand)”,       emoji:“🍞”, cat:“Féculents”,  cal:209, prot:6.8,  sat:0.3, sugar:1.2, fiber:7.5, portion:30  },
{ name:“Pomme de terre (bouillie, sans sel)”,emoji:“🥔”, cat:“Féculents”,  cal:86,  prot:2.0,  sat:0.0, sugar:0.7, fiber:1.8, portion:200 },
{ name:“Pomme de terre (cuite vapeur)”,      emoji:“🥔”, cat:“Féculents”,  cal:90,  prot:2.0,  sat:0.0, sugar:0.7, fiber:1.8, portion:200 },
{ name:“Pomme de terre (four, avec peau)”,   emoji:“🥔”, cat:“Féculents”,  cal:93,  prot:2.2,  sat:0.1, sugar:0.9, fiber:2.2, portion:200 },
{ name:“Purée (beurre + lait)”,              emoji:“🥔”, cat:“Féculents”,  cal:100, prot:2.3,  sat:2.5, sugar:1.5, fiber:1.5, portion:200 },
{ name:“Frites (cuites au four)”,            emoji:“🥔”, cat:“Féculents”,  cal:172, prot:3.0,  sat:1.0, sugar:0.5, fiber:2.5, portion:150 },
{ name:“Frites (friture industrielle)”,      emoji:“🥔”, cat:“Féculents”,  cal:312, prot:3.5,  sat:4.5, sugar:0.5, fiber:2.5, portion:150 },
{ name:“Chips (nature, Lay’s / Pringles)”,   emoji:“🥔”, cat:“Féculents”,  cal:536, prot:6.0,  sat:5.0, sugar:0.5, fiber:4.0, portion:30  },
{ name:“Patate douce (cuite vapeur)”,        emoji:“🍠”, cat:“Féculents”,  cal:90,  prot:1.6,  sat:0.0, sugar:4.2, fiber:3.3, portion:200 },
{ name:“Lentilles vertes (cuites)”,          emoji:“🫘”, cat:“Féculents”,  cal:116, prot:9.0,  sat:0.1, sugar:1.2, fiber:7.9, portion:150 },
{ name:“Lentilles corail (cuites)”,          emoji:“🫘”, cat:“Féculents”,  cal:100, prot:8.0,  sat:0.1, sugar:1.0, fiber:5.0, portion:150 },
{ name:“Pois chiches (cuits, en boîte)”,     emoji:“🫘”, cat:“Féculents”,  cal:164, prot:8.9,  sat:0.3, sugar:2.6, fiber:7.6, portion:150 },
{ name:“Haricots rouges (cuits, en boîte)”,  emoji:“🫘”, cat:“Féculents”,  cal:127, prot:8.7,  sat:0.1, sugar:0.3, fiber:8.7, portion:150 },
{ name:“Haricots blancs (cuits)”,            emoji:“🫘”, cat:“Féculents”,  cal:118, prot:7.8,  sat:0.1, sugar:0.5, fiber:7.4, portion:150 },
{ name:“Pois cassés (cuits)”,                emoji:“🫘”, cat:“Féculents”,  cal:118, prot:8.3,  sat:0.1, sugar:1.5, fiber:8.3, portion:150 },
{ name:“Edamame (fèves de soja, cuites)”,    emoji:“🫘”, cat:“Féculents”,  cal:121, prot:11.9, sat:0.7, sugar:2.2, fiber:5.2, portion:100 },

// ══════════════════════════════════════════
//  🥦 LÉGUMES
// ══════════════════════════════════════════
{ name:“Brocolis (cuits vapeur)”,            emoji:“🥦”, cat:“Légumes”,    cal:28,  prot:2.8,  sat:0.0, sugar:1.7, fiber:2.6, portion:150 },
{ name:“Chou-fleur (cuit)”,                  emoji:“🥦”, cat:“Légumes”,    cal:23,  prot:2.5,  sat:0.0, sugar:1.4, fiber:2.1, portion:150 },
{ name:“Chou blanc (cru)”,                   emoji:“🥬”, cat:“Légumes”,    cal:25,  prot:1.3,  sat:0.0, sugar:3.8, fiber:2.5, portion:100 },
{ name:“Chou rouge (cru)”,                   emoji:“🥬”, cat:“Légumes”,    cal:31,  prot:1.4,  sat:0.0, sugar:5.3, fiber:2.5, portion:100 },
{ name:“Chou de Bruxelles (cuits)”,          emoji:“🥦”, cat:“Légumes”,    cal:36,  prot:3.5,  sat:0.1, sugar:3.5, fiber:3.8, portion:150 },
{ name:“Courgette (cuite)”,                  emoji:“🥒”, cat:“Légumes”,    cal:18,  prot:1.4,  sat:0.0, sugar:2.3, fiber:1.1, portion:150 },
{ name:“Courgette (crue)”,                   emoji:“🥒”, cat:“Légumes”,    cal:17,  prot:1.2,  sat:0.0, sugar:2.5, fiber:1.0, portion:100 },
{ name:“Tomate (fraîche)”,                   emoji:“🍅”, cat:“Légumes”,    cal:20,  prot:0.9,  sat:0.0, sugar:2.6, fiber:1.2, portion:150 },
{ name:“Tomates cerises”,                    emoji:“🍅”, cat:“Légumes”,    cal:23,  prot:1.1,  sat:0.0, sugar:3.5, fiber:1.2, portion:100 },
{ name:“Tomates pelées (en boîte)”,          emoji:“🍅”, cat:“Légumes”,    cal:22,  prot:1.1,  sat:0.0, sugar:3.0, fiber:1.2, portion:200 },
{ name:“Concentré de tomate”,                emoji:“🍅”, cat:“Légumes”,    cal:68,  prot:4.0,  sat:0.1, sugar:8.0, fiber:3.5, portion:30  },
{ name:“Salade verte (laitue, feuilles)”,    emoji:“🥬”, cat:“Légumes”,    cal:13,  prot:1.3,  sat:0.0, sugar:0.6, fiber:1.3, portion:80  },
{ name:“Roquette”,                           emoji:“🥬”, cat:“Légumes”,    cal:25,  prot:2.6,  sat:0.1, sugar:2.1, fiber:1.6, portion:50  },
{ name:“Épinards (cuits)”,                   emoji:“🥬”, cat:“Légumes”,    cal:23,  prot:2.9,  sat:0.0, sugar:0.3, fiber:2.2, portion:150 },
{ name:“Épinards (crus, salade)”,            emoji:“🥬”, cat:“Légumes”,    cal:23,  prot:2.9,  sat:0.0, sugar:0.4, fiber:2.2, portion:80  },
{ name:“Carottes (crues)”,                   emoji:“🥕”, cat:“Légumes”,    cal:41,  prot:0.9,  sat:0.0, sugar:5.7, fiber:3.0, portion:100 },
{ name:“Carottes (cuites)”,                  emoji:“🥕”, cat:“Légumes”,    cal:35,  prot:0.8,  sat:0.0, sugar:4.8, fiber:2.8, portion:150 },
{ name:“Haricots verts (cuits)”,             emoji:“🫘”, cat:“Légumes”,    cal:35,  prot:2.1,  sat:0.0, sugar:3.6, fiber:3.4, portion:150 },
{ name:“Champignons de Paris (cuits)”,       emoji:“🍄”, cat:“Légumes”,    cal:28,  prot:2.1,  sat:0.0, sugar:1.0, fiber:1.7, portion:100 },
{ name:“Champignons de Paris (crus)”,        emoji:“🍄”, cat:“Légumes”,    cal:22,  prot:3.1,  sat:0.0, sugar:1.0, fiber:1.3, portion:100 },
{ name:“Shiitake (cuits)”,                   emoji:“🍄”, cat:“Légumes”,    cal:56,  prot:1.6,  sat:0.1, sugar:2.4, fiber:2.5, portion:100 },
{ name:“Poivron rouge (cru)”,                emoji:“🫑”, cat:“Légumes”,    cal:28,  prot:1.0,  sat:0.0, sugar:4.7, fiber:2.1, portion:100 },
{ name:“Poivron vert (cru)”,                 emoji:“🫑”, cat:“Légumes”,    cal:20,  prot:0.9,  sat:0.0, sugar:2.6, fiber:1.8, portion:100 },
{ name:“Concombre (cru, pelé)”,              emoji:“🥒”, cat:“Légumes”,    cal:12,  prot:0.7,  sat:0.0, sugar:1.7, fiber:0.5, portion:100 },
{ name:“Aubergine (cuite)”,                  emoji:“🍆”, cat:“Légumes”,    cal:28,  prot:1.0,  sat:0.0, sugar:2.4, fiber:2.7, portion:150 },
{ name:“Poireau (cuit)”,                     emoji:“🌿”, cat:“Légumes”,    cal:27,  prot:1.5,  sat:0.0, sugar:2.0, fiber:1.8, portion:150 },
{ name:“Céleri branche (cru)”,               emoji:“🌿”, cat:“Légumes”,    cal:14,  prot:0.7,  sat:0.0, sugar:1.4, fiber:1.8, portion:100 },
{ name:“Céleri-rave (cuit)”,                 emoji:“🌿”, cat:“Légumes”,    cal:39,  prot:1.5,  sat:0.0, sugar:3.5, fiber:3.0, portion:150 },
{ name:“Betterave (cuite)”,                  emoji:“🟣”, cat:“Légumes”,    cal:44,  prot:1.7,  sat:0.0, sugar:8.0, fiber:2.0, portion:100 },
{ name:“Radis (crus)”,                       emoji:“🌿”, cat:“Légumes”,    cal:20,  prot:1.0,  sat:0.0, sugar:2.0, fiber:1.6, portion:100 },
{ name:“Oignon (cru)”,                       emoji:“🧅”, cat:“Légumes”,    cal:40,  prot:1.1,  sat:0.0, sugar:5.0, fiber:1.7, portion:50  },
{ name:“Oignon (cuit / confit)”,             emoji:“🧅”, cat:“Légumes”,    cal:50,  prot:1.0,  sat:0.0, sugar:8.0, fiber:1.5, portion:50  },
{ name:“Ail (cru)”,                          emoji:“🧄”, cat:“Légumes”,    cal:149, prot:6.4,  sat:0.1, sugar:1.0, fiber:2.1, portion:5   },
{ name:“Échalote (crue)”,                    emoji:“🧅”, cat:“Légumes”,    cal:72,  prot:2.5,  sat:0.0, sugar:7.9, fiber:3.2, portion:20  },
{ name:“Petits pois (surgelés, cuits)”,      emoji:“🟢”, cat:“Légumes”,    cal:81,  prot:5.4,  sat:0.1, sugar:5.5, fiber:5.5, portion:100 },
{ name:“Maïs (en boîte, égoutté)”,           emoji:“🌽”, cat:“Légumes”,    cal:94,  prot:3.5,  sat:0.5, sugar:5.0, fiber:3.0, portion:100 },
{ name:“Avocat (Hass)”,                      emoji:“🥑”, cat:“Légumes”,    cal:167, prot:2.0,  sat:2.1, sugar:0.4, fiber:6.7, portion:80  },
{ name:“Artichaut (cuit)”,                   emoji:“🌿”, cat:“Légumes”,    cal:53,  prot:2.9,  sat:0.1, sugar:0.5, fiber:5.4, portion:150 },
{ name:“Asperges (cuites)”,                  emoji:“🌿”, cat:“Légumes”,    cal:26,  prot:2.9,  sat:0.0, sugar:1.1, fiber:2.1, portion:150 },
{ name:“Fenouil (cru)”,                      emoji:“🌿”, cat:“Légumes”,    cal:31,  prot:1.2,  sat:0.0, sugar:3.9, fiber:3.1, portion:100 },
{ name:“Navet (cuit)”,                       emoji:“🌿”, cat:“Légumes”,    cal:22,  prot:0.9,  sat:0.0, sugar:2.8, fiber:2.3, portion:150 },
{ name:“Potiron / Butternut (cuit)”,         emoji:“🎃”, cat:“Légumes”,    cal:28,  prot:0.8,  sat:0.0, sugar:3.8, fiber:1.5, portion:200 },
{ name:“Potimarron (cuit)”,                  emoji:“🎃”, cat:“Légumes”,    cal:40,  prot:1.5,  sat:0.1, sugar:5.5, fiber:2.5, portion:200 },
{ name:“Endive (crue)”,                      emoji:“🥬”, cat:“Légumes”,    cal:17,  prot:0.9,  sat:0.0, sugar:1.7, fiber:3.1, portion:100 },
{ name:“Bette / Blette (cuite)”,             emoji:“🥬”, cat:“Légumes”,    cal:20,  prot:1.8,  sat:0.0, sugar:1.1, fiber:1.6, portion:150 },
{ name:“Cresson (cru)”,                      emoji:“🌿”, cat:“Légumes”,    cal:32,  prot:3.3,  sat:0.1, sugar:0.8, fiber:1.6, portion:50  },
{ name:“Chou kale (cru)”,                    emoji:“🥬”, cat:“Légumes”,    cal:49,  prot:4.3,  sat:0.1, sugar:0.9, fiber:3.6, portion:80  },

// ══════════════════════════════════════════
//  🍎 FRUITS
// ══════════════════════════════════════════
{ name:“Pomme (Golden, Gala, Fuji…)”,        emoji:“🍎”, cat:“Fruits”,     cal:52,  prot:0.3,  sat:0.0, sugar:10.4,fiber:2.4, portion:150 },
{ name:“Poire (Williams, Conférence)”,       emoji:“🍐”, cat:“Fruits”,     cal:57,  prot:0.4,  sat:0.0, sugar:9.8, fiber:3.1, portion:150 },
{ name:“Banane”,                             emoji:“🍌”, cat:“Fruits”,     cal:89,  prot:1.1,  sat:0.1, sugar:12.2,fiber:2.6, portion:120 },
{ name:“Orange (navel, sanguine)”,           emoji:“🍊”, cat:“Fruits”,     cal:47,  prot:0.9,  sat:0.0, sugar:8.6, fiber:2.2, portion:150 },
{ name:“Clémentine / Mandarine”,             emoji:“🍊”, cat:“Fruits”,     cal:53,  prot:0.9,  sat:0.0, sugar:9.2, fiber:1.7, portion:100 },
{ name:“Citron (jus frais)”,                 emoji:“🍋”, cat:“Fruits”,     cal:22,  prot:0.4,  sat:0.0, sugar:2.4, fiber:0.3, portion:50  },
{ name:“Pamplemousse (rose)”,                emoji:“🍊”, cat:“Fruits”,     cal:42,  prot:0.8,  sat:0.0, sugar:7.0, fiber:1.6, portion:150 },
{ name:“Fraises”,                            emoji:“🍓”, cat:“Fruits”,     cal:32,  prot:0.7,  sat:0.0, sugar:4.9, fiber:2.0, portion:150 },
{ name:“Framboises”,                         emoji:“🍓”, cat:“Fruits”,     cal:52,  prot:1.2,  sat:0.0, sugar:4.4, fiber:6.5, portion:100 },
{ name:“Myrtilles (bleuets)”,                emoji:“🫐”, cat:“Fruits”,     cal:57,  prot:0.7,  sat:0.0, sugar:10.0,fiber:2.4, portion:100 },
{ name:“Mûres”,                              emoji:“🍇”, cat:“Fruits”,     cal:43,  prot:1.4,  sat:0.0, sugar:4.9, fiber:5.3, portion:100 },
{ name:“Cassis”,                             emoji:“🍇”, cat:“Fruits”,     cal:63,  prot:1.4,  sat:0.0, sugar:6.8, fiber:7.0, portion:100 },
{ name:“Raisins (blanc, rouge)”,             emoji:“🍇”, cat:“Fruits”,     cal:69,  prot:0.7,  sat:0.0, sugar:15.5,fiber:0.9, portion:100 },
{ name:“Cerises”,                            emoji:“🍒”, cat:“Fruits”,     cal:63,  prot:1.1,  sat:0.0, sugar:12.8,fiber:1.6, portion:100 },
{ name:“Abricot”,                            emoji:“🍑”, cat:“Fruits”,     cal:48,  prot:1.4,  sat:0.0, sugar:9.2, fiber:2.0, portion:100 },
{ name:“Pêche (fraîche)”,                    emoji:“🍑”, cat:“Fruits”,     cal:39,  prot:0.9,  sat:0.0, sugar:8.4, fiber:1.5, portion:150 },
{ name:“Nectarine / Brugnon”,                emoji:“🍑”, cat:“Fruits”,     cal:44,  prot:1.1,  sat:0.0, sugar:7.9, fiber:1.7, portion:150 },
{ name:“Prune / Mirabelle”,                  emoji:“🍇”, cat:“Fruits”,     cal:46,  prot:0.7,  sat:0.0, sugar:9.9, fiber:1.4, portion:100 },
{ name:“Melon (Charentais)”,                 emoji:“🍈”, cat:“Fruits”,     cal:34,  prot:0.8,  sat:0.0, sugar:7.4, fiber:0.9, portion:200 },
{ name:“Pastèque”,                           emoji:“🍉”, cat:“Fruits”,     cal:30,  prot:0.6,  sat:0.0, sugar:6.2, fiber:0.4, portion:200 },
{ name:“Kiwi (vert)”,                        emoji:“🥝”, cat:“Fruits”,     cal:61,  prot:1.1,  sat:0.0, sugar:9.0, fiber:3.0, portion:100 },
{ name:“Mangue”,                             emoji:“🥭”, cat:“Fruits”,     cal:60,  prot:0.8,  sat:0.0, sugar:13.4,fiber:1.6, portion:150 },
{ name:“Ananas (frais)”,                     emoji:“🍍”, cat:“Fruits”,     cal:50,  prot:0.5,  sat:0.0, sugar:10.0,fiber:1.4, portion:150 },
{ name:“Papaye”,                             emoji:“🍈”, cat:“Fruits”,     cal:39,  prot:0.6,  sat:0.0, sugar:7.2, fiber:1.8, portion:150 },
{ name:“Grenade (graines)”,                  emoji:“🍎”, cat:“Fruits”,     cal:83,  prot:1.7,  sat:0.1, sugar:14.0,fiber:4.0, portion:100 },
{ name:“Figues fraîches”,                    emoji:“🍈”, cat:“Fruits”,     cal:74,  prot:0.8,  sat:0.0, sugar:16.0,fiber:2.9, portion:100 },
{ name:“Figues sèches”,                      emoji:“🍈”, cat:“Fruits”,     cal:249, prot:3.1,  sat:0.1, sugar:47.9,fiber:9.8, portion:30  },
{ name:“Dattes (dénoyautées)”,               emoji:“🍈”, cat:“Fruits”,     cal:282, prot:2.5,  sat:0.0, sugar:66.5,fiber:8.0, portion:30  },
{ name:“Abricots secs”,                      emoji:“🍑”, cat:“Fruits”,     cal:241, prot:3.4,  sat:0.0, sugar:52.2,fiber:7.3, portion:30  },
{ name:“Raisins secs”,                       emoji:“🍇”, cat:“Fruits”,     cal:299, prot:3.1,  sat:0.0, sugar:65.8,fiber:4.0, portion:30  },
{ name:“Pruneaux (dénoyautés)”,              emoji:“🍇”, cat:“Fruits”,     cal:240, prot:2.2,  sat:0.0, sugar:38.1,fiber:7.1, portion:30  },
{ name:“Compote de pommes (sans sucre)”,     emoji:“🍎”, cat:“Fruits”,     cal:43,  prot:0.2,  sat:0.0, sugar:9.6, fiber:1.5, portion:100 },
{ name:“Compote de pommes (sucrée)”,         emoji:“🍎”, cat:“Fruits”,     cal:67,  prot:0.2,  sat:0.0, sugar:15.5,fiber:1.2, portion:100 },

// ══════════════════════════════════════════
//  🌰 OLÉAGINEUX & GRAINES
// ══════════════════════════════════════════
{ name:“Amandes (naturelles)”,               emoji:“🌰”, cat:“Oléagineux”, cal:579, prot:21.0, sat:3.9, sugar:3.9, fiber:12.5,portion:30  },
{ name:“Noix (cerneaux)”,                    emoji:“🌰”, cat:“Oléagineux”, cal:654, prot:15.2, sat:6.1, sugar:2.6, fiber:6.7, portion:30  },
{ name:“Noix de cajou (grillées, non salées)”,emoji:“🌰”,cat:“Oléagineux”, cal:553, prot:18.0, sat:9.2, sugar:5.9, fiber:3.3, portion:30  },
{ name:“Noisettes”,                          emoji:“🌰”, cat:“Oléagineux”, cal:628, prot:15.0, sat:4.5, sugar:4.3, fiber:9.7, portion:30  },
{ name:“Pistaches (non salées)”,             emoji:“🌰”, cat:“Oléagineux”, cal:560, prot:20.0, sat:5.4, sugar:7.7, fiber:10.6,portion:30  },
{ name:“Macadamia”,                          emoji:“🌰”, cat:“Oléagineux”, cal:718, prot:7.9,  sat:12.1,sugar:4.6, fiber:8.6, portion:30  },
{ name:“Noix du Brésil”,                     emoji:“🌰”, cat:“Oléagineux”, cal:656, prot:14.3, sat:15.1,sugar:2.3, fiber:7.5, portion:30  },
{ name:“Noix de pécan”,                      emoji:“🌰”, cat:“Oléagineux”, cal:691, prot:9.2,  sat:6.2, sugar:3.8, fiber:9.6, portion:30  },
{ name:“Cacahuètes (grillées, non salées)”,  emoji:“🥜”, cat:“Oléagineux”, cal:599, prot:25.0, sat:7.7, sugar:3.5, fiber:8.0, portion:30  },
{ name:“Beurre de cacahuète (sans sucre)”,   emoji:“🥜”, cat:“Oléagineux”, cal:588, prot:25.0, sat:10.0,sugar:9.0, fiber:6.0, portion:20  },
{ name:“Beurre d’amande”,                    emoji:“🌰”, cat:“Oléagineux”, cal:614, prot:21.0, sat:5.0, sugar:4.4, fiber:10.5,portion:20  },
{ name:“Graines de tournesol (nature)”,      emoji:“🌻”, cat:“Oléagineux”, cal:584, prot:20.8, sat:4.5, sugar:2.6, fiber:8.6, portion:20  },
{ name:“Graines de citrouille / potiron”,    emoji:“🌱”, cat:“Oléagineux”, cal:559, prot:30.2, sat:5.6, sugar:1.4, fiber:6.5, portion:20  },
{ name:“Graines de chia”,                    emoji:“🌱”, cat:“Oléagineux”, cal:486, prot:16.5, sat:3.3, sugar:0.0, fiber:34.4,portion:15  },
{ name:“Graines de lin (moulues)”,           emoji:“🌱”, cat:“Oléagineux”, cal:534, prot:18.3, sat:3.7, sugar:1.6, fiber:27.3,portion:10  },
{ name:“Graines de sésame (complètes)”,      emoji:“🌱”, cat:“Oléagineux”, cal:573, prot:17.7, sat:6.0, sugar:0.3, fiber:11.8,portion:10  },
{ name:“Graines de chanvre”,                 emoji:“🌱”, cat:“Oléagineux”, cal:553, prot:31.6, sat:3.3, sugar:1.5, fiber:4.0, portion:15  },
{ name:“Tahini (purée de sésame)”,           emoji:“🌱”, cat:“Oléagineux”, cal:595, prot:17.0, sat:8.3, sugar:0.5, fiber:9.3, portion:15  },

// ══════════════════════════════════════════
//  🫙 MATIÈRES GRASSES & CONDIMENTS
// ══════════════════════════════════════════
{ name:“Huile d’olive (vierge extra)”,       emoji:“🫙”, cat:“Matières grasses”, cal:884, prot:0.0, sat:13.8,sugar:0.0, fiber:0.0, portion:10 },
{ name:“Huile de colza”,                     emoji:“🫙”, cat:“Matières grasses”, cal:884, prot:0.0, sat:7.4, sugar:0.0, fiber:0.0, portion:10 },
{ name:“Huile de tournesol”,                 emoji:“🫙”, cat:“Matières grasses”, cal:884, prot:0.0, sat:11.3,sugar:0.0, fiber:0.0, portion:10 },
{ name:“Huile de noix de coco”,              emoji:“🫙”, cat:“Matières grasses”, cal:862, prot:0.0, sat:82.5,sugar:0.0, fiber:0.0, portion:10 },
{ name:“Beurre (doux)”,                      emoji:“🧈”, cat:“Matières grasses”, cal:717, prot:0.7, sat:50.5,sugar:0.6, fiber:0.0, portion:10 },
{ name:“Beurre (demi-sel)”,                  emoji:“🧈”, cat:“Matières grasses”, cal:714, prot:0.6, sat:50.3,sugar:0.5, fiber:0.0, portion:10 },
{ name:“Beurre allégé 41% (St Hubert…)”,     emoji:“🧈”, cat:“Matières grasses”, cal:361, prot:0.5, sat:25.0,sugar:0.8, fiber:0.0, portion:10 },
{ name:“Margarine végétale (60%)”,           emoji:“🧈”, cat:“Matières grasses”, cal:530, prot:0.1, sat:14.5,sugar:0.0, fiber:0.0, portion:10 },
{ name:“Mayonnaise (Hellmann’s / Amora)”,    emoji:“🫙”, cat:“Matières grasses”, cal:680, prot:1.5, sat:8.0, sugar:1.5, fiber:0.0, portion:15 },
{ name:“Mayonnaise allégée”,                 emoji:“🫙”, cat:“Matières grasses”, cal:290, prot:1.3, sat:3.0, sugar:5.0, fiber:0.0, portion:15 },
{ name:“Vinaigrette (huile + vinaigre)”,     emoji:“🫙”, cat:“Matières grasses”, cal:270, prot:0.2, sat:4.0, sugar:4.0, fiber:0.0, portion:15 },
{ name:“Moutarde de Dijon”,                  emoji:“🫙”, cat:“Condiments”,       cal:60,  prot:4.0, sat:0.4, sugar:2.0, fiber:3.0, portion:10 },
{ name:“Moutarde à l’ancienne”,              emoji:“🫙”, cat:“Condiments”,       cal:64,  prot:3.8, sat:0.5, sugar:2.5, fiber:3.2, portion:10 },
{ name:“Ketchup (Heinz)”,                    emoji:“🫙”, cat:“Condiments”,       cal:100, prot:1.5, sat:0.1, sugar:22.0,fiber:0.5, portion:15 },
{ name:“Sauce soja (Kikkoman)”,              emoji:“🫙”, cat:“Condiments”,       cal:43,  prot:6.5, sat:0.0, sugar:0.6, fiber:0.0, portion:15 },
{ name:“Sauce soja sucrée (teriyaki)”,       emoji:“🫙”, cat:“Condiments”,       cal:87,  prot:3.5, sat:0.0, sugar:17.0,fiber:0.1, portion:15 },
{ name:“Sauce Worcester”,                    emoji:“🫙”, cat:“Condiments”,       cal:78,  prot:1.5, sat:0.0, sugar:18.0,fiber:0.0, portion:10 },
{ name:“Sauce tabasco”,                      emoji:“🫙”, cat:“Condiments”,       cal:12,  prot:0.5, sat:0.0, sugar:0.5, fiber:0.5, portion:5  },
{ name:“Sauce sriracha”,                     emoji:“🫙”, cat:“Condiments”,       cal:93,  prot:1.8, sat:0.3, sugar:16.0,fiber:0.5, portion:10 },
{ name:“Vinaigre de cidre”,                  emoji:“🫙”, cat:“Condiments”,       cal:21,  prot:0.0, sat:0.0, sugar:0.4, fiber:0.0, portion:15 },
{ name:“Vinaigre balsamique (Modène)”,       emoji:“🫙”, cat:“Condiments”,       cal:88,  prot:0.5, sat:0.0, sugar:17.0,fiber:0.0, portion:10 },
{ name:“Pesto (genovese)”,                   emoji:“🫙”, cat:“Condiments”,       cal:470, prot:5.0, sat:10.0,sugar:1.5, fiber:2.0, portion:20 },
{ name:“Sauce tomate (Barilla / Panzani)”,   emoji:“🫙”, cat:“Condiments”,       cal:55,  prot:1.5, sat:0.4, sugar:7.5, fiber:1.5, portion:100},
{ name:“Houmous (purée de pois chiches)”,    emoji:“🫙”, cat:“Condiments”,       cal:166, prot:7.9, sat:1.5, sugar:0.5, fiber:6.0, portion:50 },
{ name:“Guacamole (maison)”,                 emoji:“🥑”, cat:“Condiments”,       cal:152, prot:1.8, sat:2.0, sugar:0.6, fiber:5.5, portion:50 },

// ══════════════════════════════════════════
//  🥣 PETIT-DÉJEUNER & TARTINES
// ══════════════════════════════════════════
{ name:“Confiture (fraise, framboise…)”,     emoji:“🍓”, cat:“Petit-déj”,  cal:250, prot:0.4,  sat:0.0, sugar:60.0,fiber:0.5, portion:20  },
{ name:“Confiture allégée (sans sucre)”,     emoji:“🍓”, cat:“Petit-déj”,  cal:100, prot:0.5,  sat:0.0, sugar:20.0,fiber:0.5, portion:20  },
{ name:“Miel (toutes fleurs)”,               emoji:“🍯”, cat:“Petit-déj”,  cal:304, prot:0.3,  sat:0.0, sugar:82.0,fiber:0.0, portion:10  },
{ name:“Nutella (pâte choc. noisette)”,      emoji:“🍫”, cat:“Petit-déj”,  cal:539, prot:6.3,  sat:10.6,sugar:56.7,fiber:3.0, portion:20  },
{ name:“Speculoos (pâte à tartiner)”,        emoji:“🍪”, cat:“Petit-déj”,  cal:540, prot:5.5,  sat:11.0,sugar:42.0,fiber:1.0, portion:20  },
{ name:“Crêpe nature (maison, 50g)”,         emoji:“🥞”, cat:“Petit-déj”,  cal:197, prot:6.0,  sat:2.5, sugar:5.5, fiber:0.8, portion:80  },
{ name:“Gaufre (industrielle)”,              emoji:“🧇”, cat:“Petit-déj”,  cal:385, prot:6.5,  sat:5.5, sugar:22.0,fiber:1.0, portion:70  },
{ name:“Pancake (maison, farine + lait)”,    emoji:“🥞”, cat:“Petit-déj”,  cal:210, prot:6.5,  sat:2.8, sugar:8.0, fiber:0.8, portion:80  },
{ name:“Pain perdu (brioche)”,               emoji:“🍞”, cat:“Petit-déj”,  cal:280, prot:8.0,  sat:5.0, sugar:18.0,fiber:0.5, portion:100 },
{ name:“Granola (maison, avoine + miel)”,    emoji:“🌾”, cat:“Petit-déj”,  cal:450, prot:10.0, sat:4.0, sugar:18.0,fiber:6.0, portion:50  },
{ name:“Porridge (avoine + lait demi-écrémé)”,emoji:“🌾”,cat:“Petit-déj”, cal:120, prot:5.0,  sat:0.8, sugar:5.0, fiber:2.5, portion:250 },
{ name:“Smoothie banane-fraise (maison)”,    emoji:“🥤”, cat:“Petit-déj”,  cal:75,  prot:1.5,  sat:0.1, sugar:14.5,fiber:1.5, portion:250 },

// ══════════════════════════════════════════
//  ☕ BOISSONS
// ══════════════════════════════════════════
{ name:“Eau (plate ou gazeuse)”,             emoji:“💧”, cat:“Boissons”,   cal:0,   prot:0.0,  sat:0.0, sugar:0.0, fiber:0.0, portion:250 },
{ name:“Café (expresso, noir, sans sucre)”,  emoji:“☕”, cat:“Boissons”,   cal:2,   prot:0.3,  sat:0.0, sugar:0.0, fiber:0.0, portion:30  },
{ name:“Café (filtre, long, sans sucre)”,    emoji:“☕”, cat:“Boissons”,   cal:2,   prot:0.3,  sat:0.0, sugar:0.0, fiber:0.0, portion:250 },
{ name:“Café (cappuccino, lait entier)”,     emoji:“☕”, cat:“Boissons”,   cal:74,  prot:4.0,  sat:2.2, sugar:6.5, fiber:0.0, portion:200 },
{ name:“Café (latte macchiato, lait 1/2)”,   emoji:“☕”, cat:“Boissons”,   cal:85,  prot:4.5,  sat:1.5, sugar:9.0, fiber:0.0, portion:300 },
{ name:“Thé (vert, noir, infusion, sans sucre)”,emoji:“🍵”,cat:“Boissons”, cal:1,  prot:0.0,  sat:0.0, sugar:0.0, fiber:0.0, portion:250 },
{ name:“Jus d’orange (100% pur jus)”,        emoji:“🍊”, cat:“Boissons”,   cal:44,  prot:0.7,  sat:0.0, sugar:8.4, fiber:0.2, portion:200 },
{ name:“Jus de pomme (100% pur jus)”,        emoji:“🍎”, cat:“Boissons”,   cal:47,  prot:0.1,  sat:0.0, sugar:10.3,fiber:0.1, portion:200 },
{ name:“Coca-Cola (original)”,               emoji:“🥤”, cat:“Boissons”,   cal:42,  prot:0.0,  sat:0.0, sugar:10.6,fiber:0.0, portion:330 },
{ name:“Coca-Cola Zero”,                     emoji:“🥤”, cat:“Boissons”,   cal:1,   prot:0.0,  sat:0.0, sugar:0.0, fiber:0.0, portion:330 },
{ name:“Limonade / Sprite (sucré)”,          emoji:“🥤”, cat:“Boissons”,   cal:40,  prot:0.0,  sat:0.0, sugar:9.9, fiber:0.0, portion:330 },
{ name:“Jus de raisin (100%)”,               emoji:“🍇”, cat:“Boissons”,   cal:60,  prot:0.4,  sat:0.0, sugar:14.2,fiber:0.0, portion:200 },
{ name:“Eau de coco (100% naturelle)”,       emoji:“🥥”, cat:“Boissons”,   cal:19,  prot:0.7,  sat:0.0, sugar:2.6, fiber:1.1, portion:250 },
{ name:“Boisson protéinée (whey + eau)”,     emoji:“💪”, cat:“Boissons”,   cal:110, prot:22.0, sat:0.5, sugar:1.5, fiber:0.0, portion:300 },
{ name:“Kombucha (nature, peu sucré)”,       emoji:“🥤”, cat:“Boissons”,   cal:8,   prot:0.0,  sat:0.0, sugar:1.5, fiber:0.0, portion:250 },
{ name:“Bière blonde (5%)”,                  emoji:“🍺”, cat:“Boissons”,   cal:43,  prot:0.5,  sat:0.0, sugar:3.5, fiber:0.0, portion:330 },
{ name:“Bière légère / sans alcool”,         emoji:“🍺”, cat:“Boissons”,   cal:24,  prot:0.5,  sat:0.0, sugar:4.0, fiber:0.0, portion:330 },
{ name:“Vin rouge (12%)”,                    emoji:“🍷”, cat:“Boissons”,   cal:85,  prot:0.1,  sat:0.0, sugar:0.2, fiber:0.0, portion:150 },
{ name:“Vin blanc sec (12%)”,                emoji:“🍷”, cat:“Boissons”,   cal:82,  prot:0.1,  sat:0.0, sugar:0.6, fiber:0.0, portion:150 },
{ name:“Champagne / Crémant (brut)”,         emoji:“🥂”, cat:“Boissons”,   cal:80,  prot:0.3,  sat:0.0, sugar:1.0, fiber:0.0, portion:120 },

// ══════════════════════════════════════════
//  🍫 SUCRERIES & SNACKS
// ══════════════════════════════════════════
{ name:“Chocolat noir 70% (Lindt, Valrhona)”,emoji:“🍫”, cat:“Sucreries”,  cal:598, prot:8.0,  sat:19.0,sugar:24.0,fiber:11.0,portion:20  },
{ name:“Chocolat noir 85%”,                  emoji:“🍫”, cat:“Sucreries”,  cal:620, prot:10.0, sat:20.0,sugar:14.0,fiber:14.0,portion:20  },
{ name:“Chocolat au lait (Milka, Nestlé…)”,  emoji:“🍫”, cat:“Sucreries”,  cal:535, prot:7.5,  sat:19.0,sugar:56.0,fiber:3.0, portion:20  },
{ name:“Chocolat blanc”,                     emoji:“🍫”, cat:“Sucreries”,  cal:539, prot:5.9,  sat:19.4,sugar:59.0,fiber:0.0, portion:20  },
{ name:“Kit Kat (barre, 41g)”,               emoji:“🍫”, cat:“Sucreries”,  cal:508, prot:6.5,  sat:14.0,sugar:49.0,fiber:1.5, portion:41  },
{ name:“Snickers (barre, 50g)”,              emoji:“🍫”, cat:“Sucreries”,  cal:488, prot:8.5,  sat:8.3, sugar:52.0,fiber:1.8, portion:50  },
{ name:“Twix (barre, 50g)”,                  emoji:“🍫”, cat:“Sucreries”,  cal:494, prot:4.5,  sat:10.0,sugar:52.0,fiber:1.0, portion:50  },
{ name:“Biscuit sablé (Lu, Bahlsen…)”,       emoji:“🍪”, cat:“Sucreries”,  cal:480, prot:5.5,  sat:10.0,sugar:22.0,fiber:1.5, portion:20  },
{ name:“Petit Lu / Petit Beurre”,            emoji:“🍪”, cat:“Sucreries”,  cal:439, prot:7.5,  sat:6.5, sugar:23.0,fiber:1.5, portion:20  },
{ name:“Oreo (biscuit)”,                     emoji:“🍪”, cat:“Sucreries”,  cal:473, prot:4.9,  sat:7.0, sugar:40.0,fiber:2.0, portion:11  },
{ name:“Prince (biscuit chocolat)”,          emoji:“🍪”, cat:“Sucreries”,  cal:467, prot:6.5,  sat:8.5, sugar:30.0,fiber:2.5, portion:28  },
{ name:“Spéculoos”,                          emoji:“🍪”, cat:“Sucreries”,  cal:479, prot:5.5,  sat:8.5, sugar:32.0,fiber:2.0, portion:14  },
{ name:“Croissant (beurre)”,                 emoji:“🥐”, cat:“Sucreries”,  cal:406, prot:7.5,  sat:12.0,sugar:6.0, fiber:2.0, portion:55  },
{ name:“Pain au chocolat”,                   emoji:“🥐”, cat:“Sucreries”,  cal:370, prot:7.0,  sat:10.0,sugar:14.0,fiber:2.5, portion:80  },
{ name:“Brioche (nature)”,                   emoji:“🍞”, cat:“Sucreries”,  cal:370, prot:8.5,  sat:8.5, sugar:16.5,fiber:1.5, portion:50  },
{ name:“Madeleine (maison)”,                 emoji:“🍰”, cat:“Sucreries”,  cal:410, prot:6.5,  sat:8.0, sugar:32.0,fiber:1.0, portion:35  },
{ name:“Muffin (bleuets, industriel)”,       emoji:“🧁”, cat:“Sucreries”,  cal:375, prot:5.0,  sat:4.5, sugar:28.0,fiber:1.5, portion:100 },
{ name:“Gâteau au yaourt (maison)”,          emoji:“🎂”, cat:“Sucreries”,  cal:310, prot:5.5,  sat:5.0, sugar:30.0,fiber:0.8, portion:80  },
{ name:“Tarte aux pommes (maison)”,          emoji:“🥧”, cat:“Sucreries”,  cal:255, prot:3.5,  sat:4.5, sugar:20.0,fiber:1.5, portion:120 },
{ name:“Éclair au chocolat”,                 emoji:“🍰”, cat:“Sucreries”,  cal:303, prot:6.0,  sat:5.5, sugar:28.0,fiber:1.0, portion:100 },
{ name:“Glace vanille (bac)”,                emoji:“🍦”, cat:“Sucreries”,  cal:207, prot:3.5,  sat:7.5, sugar:22.0,fiber:0.0, portion:75  },
{ name:“Glace chocolat (bac)”,               emoji:“🍦”, cat:“Sucreries”,  cal:216, prot:3.8,  sat:7.8, sugar:23.0,fiber:1.5, portion:75  },
{ name:“Sorbet citron / framboise”,          emoji:“🍧”, cat:“Sucreries”,  cal:130, prot:0.5,  sat:0.0, sugar:30.0,fiber:0.3, portion:75  },
{ name:“Sucre blanc (cristal / en poudre)”,  emoji:“🍬”, cat:“Sucreries”,  cal:400, prot:0.0,  sat:0.0, sugar:100.0,fiber:0.0,portion:5   },
{ name:“Sucre roux / cassonade”,             emoji:“🍬”, cat:“Sucreries”,  cal:395, prot:0.0,  sat:0.0, sugar:98.0,fiber:0.0, portion:5   },
{ name:“Sirop d’érable”,                     emoji:“🍯”, cat:“Sucreries”,  cal:260, prot:0.0,  sat:0.0, sugar:60.5,fiber:0.0, portion:15  },

// ══════════════════════════════════════════
//  🍕 PLATS CUISINÉS & FAST-FOOD
// ══════════════════════════════════════════
{ name:“Pizza margherita (part, 120g)”,      emoji:“🍕”, cat:“Plats”,      cal:266, prot:11.0, sat:4.0, sugar:4.5, fiber:2.0, portion:120 },
{ name:“Pizza 4 fromages (part, 120g)”,      emoji:“🍕”, cat:“Plats”,      cal:320, prot:14.0, sat:8.0, sugar:3.5, fiber:1.5, portion:120 },
{ name:“Hamburger maison (steak + pain)”,    emoji:“🍔”, cat:“Plats”,      cal:295, prot:18.0, sat:7.0, sugar:5.0, fiber:1.5, portion:200 },
{ name:“Big Mac (McDonald’s)”,               emoji:“🍔”, cat:“Plats”,      cal:257, prot:13.0, sat:6.0, sugar:6.0, fiber:1.5, portion:200 },
{ name:“Quiche lorraine (part)”,             emoji:“🥧”, cat:“Plats”,      cal:340, prot:12.0, sat:12.0,sugar:3.0, fiber:0.5, portion:130 },
{ name:“Lasagnes bolognaise (plat cuisiné)”, emoji:“🍝”, cat:“Plats”,      cal:150, prot:9.0,  sat:3.5, sugar:4.0, fiber:1.0, portion:300 },
{ name:“Gratin dauphinois”,                  emoji:“🥔”, cat:“Plats”,      cal:165, prot:4.0,  sat:6.0, sugar:2.0, fiber:1.5, portion:200 },
{ name:“Hachis parmentier”,                  emoji:“🥔”, cat:“Plats”,      cal:140, prot:8.5,  sat:3.5, sugar:2.5, fiber:1.5, portion:300 },
{ name:“Soupe de légumes (maison)”,          emoji:“🍲”, cat:“Plats”,      cal:48,  prot:2.0,  sat:0.2, sugar:4.0, fiber:2.5, portion:300 },
{ name:“Minestrone (maison)”,                emoji:“🍲”, cat:“Plats”,      cal:62,  prot:3.0,  sat:0.3, sugar:4.5, fiber:3.0, portion:300 },
{ name:“Taboulé libanais (maison)”,          emoji:“🥗”, cat:“Plats”,      cal:100, prot:2.5,  sat:1.0, sugar:3.0, fiber:2.5, portion:200 },
{ name:“Salade niçoise (complète)”,          emoji:“🥗”, cat:“Plats”,      cal:130, prot:12.0, sat:2.0, sugar:3.0, fiber:2.5, portion:300 },
{ name:“Salade César (poulet + parmesan)”,   emoji:“🥗”, cat:“Plats”,      cal:175, prot:14.0, sat:3.5, sugar:2.5, fiber:1.5, portion:300 },
{ name:“Ratatouille (maison)”,               emoji:“🍲”, cat:“Plats”,      cal:55,  prot:1.8,  sat:0.5, sugar:5.0, fiber:3.0, portion:200 },
{ name:“Chili con carne (maison)”,           emoji:“🌶️”, cat:“Plats”,     cal:152, prot:11.0, sat:2.5, sugar:4.5, fiber:4.5, portion:300 },
{ name:“Curry de poulet (lait de coco)”,     emoji:“🍛”, cat:“Plats”,      cal:145, prot:12.0, sat:5.0, sugar:4.0, fiber:1.5, portion:300 },
{ name:“Sushi (maki concombre, 1 pièce)”,    emoji:“🍱”, cat:“Plats”,      cal:28,  prot:0.9,  sat:0.0, sugar:1.0, fiber:0.2, portion:25  },
{ name:“Sushi (saumon nigiri, 1 pièce)”,     emoji:“🍱”, cat:“Plats”,      cal:42,  prot:3.5,  sat:0.3, sugar:1.5, fiber:0.0, portion:30  },
{ name:“Ramen (bouillon + nouilles + œuf)”,  emoji:“🍜”, cat:“Plats”,      cal:95,  prot:6.0,  sat:1.5, sugar:3.0, fiber:1.0, portion:500 },
{ name:“Pad thaï (crevettes)”,               emoji:“🍜”, cat:“Plats”,      cal:168, prot:9.0,  sat:1.5, sugar:6.5, fiber:1.5, portion:300 },
{ name:“Couscous royal (viande + merguez)”,  emoji:“🍲”, cat:“Plats”,      cal:185, prot:12.0, sat:4.5, sugar:4.0, fiber:3.0, portion:400 },
{ name:“Tajine poulet citron confit”,        emoji:“🫕”, cat:“Plats”,      cal:155, prot:14.0, sat:3.0, sugar:3.5, fiber:2.0, portion:300 },
{ name:“Blanquette de veau (maison)”,        emoji:“🫕”, cat:“Plats”,      cal:148, prot:13.0, sat:4.5, sugar:3.0, fiber:1.0, portion:300 },
{ name:“Bœuf bourguignon (maison)”,         emoji:“🫕”, cat:“Plats”,      cal:145, prot:14.0, sat:4.0, sugar:4.0, fiber:1.5, portion:350 },

// ══════════════════════════════════════════
//  💪 NUTRITION SPORTIVE
// ══════════════════════════════════════════
{ name:“Whey protéine (chocolat, 1 dose)”,   emoji:“💪”, cat:“Sport”,      cal:120, prot:24.0, sat:0.8, sugar:2.5, fiber:0.5, portion:30  },
{ name:“Whey protéine (vanille, 1 dose)”,    emoji:“💪”, cat:“Sport”,      cal:116, prot:23.5, sat:0.5, sugar:3.5, fiber:0.3, portion:30  },
{ name:“Caséine (nuit, protéine lente)”,     emoji:“💪”, cat:“Sport”,      cal:114, prot:24.0, sat:0.4, sugar:2.0, fiber:0.5, portion:30  },
{ name:“Barre protéinée (Quest, 60g)”,       emoji:“💪”, cat:“Sport”,      cal:200, prot:21.0, sat:3.5, sugar:1.0, fiber:15.0,portion:60  },
{ name:“Barre énergétique (Clif Bar, 68g)”,  emoji:“⚡”, cat:“Sport”,      cal:250, prot:9.0,  sat:1.5, sugar:22.0,fiber:5.0, portion:68  },
{ name:“Gel énergétique (Maurten / SiS)”,    emoji:“⚡”, cat:“Sport”,      cal:100, prot:0.0,  sat:0.0, sugar:22.0,fiber:0.0, portion:40  },
{ name:“Boisson isotonique (Gatorade, 500ml)”,emoji:“🥤”,cat:“Sport”,      cal:30,  prot:0.0,  sat:0.0, sugar:6.0, fiber:0.0, portion:500 },
];

// ── Catégories ──────────────────────────────
const FOOD_CATEGORIES = [
“Volailles”,“Viandes”,“Poissons”,“Œufs”,“Laitiers”,“Fromages”,
“Féculents”,“Légumes”,“Fruits”,“Oléagineux”,
“Matières grasses”,“Condiments”,“Petit-déj”,“Boissons”,“Sucreries”,“Plats”,“Sport”
];

// ── Export (Node.js / require) ───────────────
if (typeof module !== ‘undefined’) {
module.exports = { FOODS_DB, FOOD_CATEGORIES };
}
